package com.zhe800.quartz.model.mapper;

import com.zhe800.quartz.model.pojo.TbWithdrawals;
import com.zhe800.quartz.model.pojo.TbWithdrawalsExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface TbWithdrawalsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_withdrawals
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    int countByExample(TbWithdrawalsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_withdrawals
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    int deleteByExample(TbWithdrawalsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_withdrawals
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    @Delete({
        "delete from tb_withdrawals",
        "where serial_number = #{serialNumber,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer serialNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_withdrawals
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    @Insert({
        "insert into tb_withdrawals (daybook_serial_number, seller_id, ",
        "amount, bank_id, ",
        "bank_name, bank_province, ",
        "bank_city, bank_full_name, ",
        "account_code, name, ",
        "nickname, apply_people, ",
        "apply_time, ",
        "handle_people, handle_time, ",
        "status, status_before_freezing, ",
        "preprocess_time, agree_time, ",
        "is_modify, account_type, ",
        "real_poundage, poundage, ",
        "real_amount, task_id, ",
        "complete_time, ",
        "failure_reason, image_path)",
        "values (#{daybookSerialNumber,jdbcType=BIGINT}, #{sellerId,jdbcType=INTEGER}, ",
        "#{amount,jdbcType=INTEGER}, #{bankId,jdbcType=INTEGER}, ",
        "#{bankName,jdbcType=VARCHAR}, #{bankProvince,jdbcType=VARCHAR}, ",
        "#{bankCity,jdbcType=VARCHAR}, #{bankFullName,jdbcType=VARCHAR}, ",
        "#{accountCode,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{nickname,jdbcType=VARCHAR}, #{applyPeople,jdbcType=VARCHAR}, ",
        "#{applyTime,jdbcType=TIMESTAMP,typeHandler=com.tuan800.mybatis.typehandler.JodaDateTime2TimestampTypeHandler}, ",
        "#{handlePeople,jdbcType=VARCHAR}, #{handleTime,jdbcType=TIMESTAMP,typeHandler=com.tuan800.mybatis.typehandler.JodaDateTime2TimestampTypeHandler}, ",
        "#{status,jdbcType=TINYINT}, #{statusBeforeFreezing,jdbcType=TINYINT}, ",
        "#{preprocessTime,jdbcType=TINYINT}, #{agreeTime,jdbcType=TIMESTAMP,typeHandler=com.tuan800.mybatis.typehandler.JodaDateTime2TimestampTypeHandler}, ",
        "#{isModify,jdbcType=TINYINT}, #{accountType,jdbcType=TINYINT}, ",
        "#{realPoundage,jdbcType=INTEGER}, #{poundage,jdbcType=INTEGER}, ",
        "#{realAmount,jdbcType=INTEGER}, #{taskId,jdbcType=INTEGER}, ",
        "#{completeTime,jdbcType=TIMESTAMP,typeHandler=com.tuan800.mybatis.typehandler.JodaDateTime2TimestampTypeHandler}, ",
        "#{failureReason,jdbcType=VARCHAR}, #{imagePath,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="serialNumber", before=false, resultType=Integer.class)
    int insert(TbWithdrawals record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_withdrawals
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    int insertSelective(TbWithdrawals record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_withdrawals
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    List<TbWithdrawals> selectByExample(TbWithdrawalsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_withdrawals
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    @Select({
        "select",
        "serial_number, daybook_serial_number, seller_id, amount, bank_id, bank_name, ",
        "bank_province, bank_city, bank_full_name, account_code, name, nickname, apply_people, ",
        "apply_time, handle_people, handle_time, status, status_before_freezing, preprocess_time, ",
        "agree_time, is_modify, account_type, real_poundage, poundage, real_amount, task_id, ",
        "complete_time, failure_reason, image_path",
        "from tb_withdrawals",
        "where serial_number = #{serialNumber,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    TbWithdrawals selectByPrimaryKey(Integer serialNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_withdrawals
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    int updateByExampleSelective(@Param("record") TbWithdrawals record, @Param("example") TbWithdrawalsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_withdrawals
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    int updateByExample(@Param("record") TbWithdrawals record, @Param("example") TbWithdrawalsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_withdrawals
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    int updateByPrimaryKeySelective(TbWithdrawals record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_withdrawals
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    @Update({
        "update tb_withdrawals",
        "set daybook_serial_number = #{daybookSerialNumber,jdbcType=BIGINT},",
          "seller_id = #{sellerId,jdbcType=INTEGER},",
          "amount = #{amount,jdbcType=INTEGER},",
          "bank_id = #{bankId,jdbcType=INTEGER},",
          "bank_name = #{bankName,jdbcType=VARCHAR},",
          "bank_province = #{bankProvince,jdbcType=VARCHAR},",
          "bank_city = #{bankCity,jdbcType=VARCHAR},",
          "bank_full_name = #{bankFullName,jdbcType=VARCHAR},",
          "account_code = #{accountCode,jdbcType=VARCHAR},",
          "name = #{name,jdbcType=VARCHAR},",
          "nickname = #{nickname,jdbcType=VARCHAR},",
          "apply_people = #{applyPeople,jdbcType=VARCHAR},",
          "apply_time = #{applyTime,jdbcType=TIMESTAMP,typeHandler=com.tuan800.mybatis.typehandler.JodaDateTime2TimestampTypeHandler},",
          "handle_people = #{handlePeople,jdbcType=VARCHAR},",
          "handle_time = #{handleTime,jdbcType=TIMESTAMP,typeHandler=com.tuan800.mybatis.typehandler.JodaDateTime2TimestampTypeHandler},",
          "status = #{status,jdbcType=TINYINT},",
          "status_before_freezing = #{statusBeforeFreezing,jdbcType=TINYINT},",
          "preprocess_time = #{preprocessTime,jdbcType=TINYINT},",
          "agree_time = #{agreeTime,jdbcType=TIMESTAMP,typeHandler=com.tuan800.mybatis.typehandler.JodaDateTime2TimestampTypeHandler},",
          "is_modify = #{isModify,jdbcType=TINYINT},",
          "account_type = #{accountType,jdbcType=TINYINT},",
          "real_poundage = #{realPoundage,jdbcType=INTEGER},",
          "poundage = #{poundage,jdbcType=INTEGER},",
          "real_amount = #{realAmount,jdbcType=INTEGER},",
          "task_id = #{taskId,jdbcType=INTEGER},",
          "complete_time = #{completeTime,jdbcType=TIMESTAMP,typeHandler=com.tuan800.mybatis.typehandler.JodaDateTime2TimestampTypeHandler},",
          "failure_reason = #{failureReason,jdbcType=VARCHAR},",
          "image_path = #{imagePath,jdbcType=VARCHAR}",
        "where serial_number = #{serialNumber,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TbWithdrawals record);
}