package com.zhe800.quartz.model.pojo;

import org.joda.time.DateTime;

public class TbQuartzTask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_quartz_task.task_id
     *
     * @mbggenerated Thu Apr 02 11:06:17 CST 2015
     */
    private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_quartz_task.task_name
     *
     * @mbggenerated Thu Apr 02 11:06:17 CST 2015
     */
    private String taskName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_quartz_task.task_group
     *
     * @mbggenerated Thu Apr 02 11:06:17 CST 2015
     */
    private String taskGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_quartz_task.task_des
     *
     * @mbggenerated Thu Apr 02 11:06:17 CST 2015
     */
    private String taskDes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_quartz_task.task_url
     *
     * @mbggenerated Thu Apr 02 11:06:17 CST 2015
     */
    private String taskUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_quartz_task.task_express
     *
     * @mbggenerated Thu Apr 02 11:06:17 CST 2015
     */
    private String taskExpress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_quartz_task.task_key
     *
     * @mbggenerated Thu Apr 02 11:06:17 CST 2015
     */
    private String taskKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_quartz_task.task_status
     *
     * @mbggenerated Thu Apr 02 11:06:17 CST 2015
     */
    private Byte taskStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_quartz_task.create_time
     *
     * @mbggenerated Thu Apr 02 11:06:17 CST 2015
     */
    private DateTime createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_quartz_task.last_update_time
     *
     * @mbggenerated Thu Apr 02 11:06:17 CST 2015
     */
    private DateTime lastUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_quartz_task.task_id
     *
     * @return the value of tb_quartz_task.task_id
     *
     * @mbggenerated Thu Apr 02 11:06:17 CST 2015
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_quartz_task.task_id
     *
     * @param taskId the value for tb_quartz_task.task_id
     *
     * @mbggenerated Thu Apr 02 11:06:17 CST 2015
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_quartz_task.task_name
     *
     * @return the value of tb_quartz_task.task_name
     *
     * @mbggenerated Thu Apr 02 11:06:17 CST 2015
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_quartz_task.task_name
     *
     * @param taskName the value for tb_quartz_task.task_name
     *
     * @mbggenerated Thu Apr 02 11:06:17 CST 2015
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_quartz_task.task_group
     *
     * @return the value of tb_quartz_task.task_group
     *
     * @mbggenerated Thu Apr 02 11:06:17 CST 2015
     */
    public String getTaskGroup() {
        return taskGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_quartz_task.task_group
     *
     * @param taskGroup the value for tb_quartz_task.task_group
     *
     * @mbggenerated Thu Apr 02 11:06:17 CST 2015
     */
    public void setTaskGroup(String taskGroup) {
        this.taskGroup = taskGroup == null ? null : taskGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_quartz_task.task_des
     *
     * @return the value of tb_quartz_task.task_des
     *
     * @mbggenerated Thu Apr 02 11:06:17 CST 2015
     */
    public String getTaskDes() {
        return taskDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_quartz_task.task_des
     *
     * @param taskDes the value for tb_quartz_task.task_des
     *
     * @mbggenerated Thu Apr 02 11:06:17 CST 2015
     */
    public void setTaskDes(String taskDes) {
        this.taskDes = taskDes == null ? null : taskDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_quartz_task.task_url
     *
     * @return the value of tb_quartz_task.task_url
     *
     * @mbggenerated Thu Apr 02 11:06:17 CST 2015
     */
    public String getTaskUrl() {
        return taskUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_quartz_task.task_url
     *
     * @param taskUrl the value for tb_quartz_task.task_url
     *
     * @mbggenerated Thu Apr 02 11:06:17 CST 2015
     */
    public void setTaskUrl(String taskUrl) {
        this.taskUrl = taskUrl == null ? null : taskUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_quartz_task.task_express
     *
     * @return the value of tb_quartz_task.task_express
     *
     * @mbggenerated Thu Apr 02 11:06:17 CST 2015
     */
    public String getTaskExpress() {
        return taskExpress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_quartz_task.task_express
     *
     * @param taskExpress the value for tb_quartz_task.task_express
     *
     * @mbggenerated Thu Apr 02 11:06:17 CST 2015
     */
    public void setTaskExpress(String taskExpress) {
        this.taskExpress = taskExpress == null ? null : taskExpress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_quartz_task.task_key
     *
     * @return the value of tb_quartz_task.task_key
     *
     * @mbggenerated Thu Apr 02 11:06:17 CST 2015
     */
    public String getTaskKey() {
        return taskKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_quartz_task.task_key
     *
     * @param taskKey the value for tb_quartz_task.task_key
     *
     * @mbggenerated Thu Apr 02 11:06:17 CST 2015
     */
    public void setTaskKey(String taskKey) {
        this.taskKey = taskKey == null ? null : taskKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_quartz_task.task_status
     *
     * @return the value of tb_quartz_task.task_status
     *
     * @mbggenerated Thu Apr 02 11:06:17 CST 2015
     */
    public Byte getTaskStatus() {
        return taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_quartz_task.task_status
     *
     * @param taskStatus the value for tb_quartz_task.task_status
     *
     * @mbggenerated Thu Apr 02 11:06:17 CST 2015
     */
    public void setTaskStatus(Byte taskStatus) {
        this.taskStatus = taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_quartz_task.create_time
     *
     * @return the value of tb_quartz_task.create_time
     *
     * @mbggenerated Thu Apr 02 11:06:17 CST 2015
     */
    public DateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_quartz_task.create_time
     *
     * @param createTime the value for tb_quartz_task.create_time
     *
     * @mbggenerated Thu Apr 02 11:06:17 CST 2015
     */
    public void setCreateTime(DateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_quartz_task.last_update_time
     *
     * @return the value of tb_quartz_task.last_update_time
     *
     * @mbggenerated Thu Apr 02 11:06:17 CST 2015
     */
    public DateTime getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_quartz_task.last_update_time
     *
     * @param lastUpdateTime the value for tb_quartz_task.last_update_time
     *
     * @mbggenerated Thu Apr 02 11:06:17 CST 2015
     */
    public void setLastUpdateTime(DateTime lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
}