package com.zhe800.quartz.model.pojo;

import org.joda.time.DateTime;

public class TbWithdrawals {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdrawals.serial_number
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    private Integer serialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdrawals.daybook_serial_number
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    private Long daybookSerialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdrawals.seller_id
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    private Integer sellerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdrawals.amount
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdrawals.bank_id
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    private Integer bankId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdrawals.bank_name
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdrawals.bank_province
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    private String bankProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdrawals.bank_city
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    private String bankCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdrawals.bank_full_name
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    private String bankFullName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdrawals.account_code
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    private String accountCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdrawals.name
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdrawals.nickname
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdrawals.apply_people
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    private String applyPeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdrawals.apply_time
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    private DateTime applyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdrawals.handle_people
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    private String handlePeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdrawals.handle_time
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    private DateTime handleTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdrawals.status
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdrawals.status_before_freezing
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    private Byte statusBeforeFreezing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdrawals.preprocess_time
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    private Byte preprocessTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdrawals.agree_time
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    private DateTime agreeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdrawals.is_modify
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    private Byte isModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdrawals.account_type
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    private Byte accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdrawals.real_poundage
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    private Integer realPoundage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdrawals.poundage
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    private Integer poundage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdrawals.real_amount
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    private Integer realAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdrawals.task_id
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdrawals.complete_time
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    private DateTime completeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdrawals.failure_reason
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    private String failureReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdrawals.image_path
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    private String imagePath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdrawals.serial_number
     *
     * @return the value of tb_withdrawals.serial_number
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public Integer getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdrawals.serial_number
     *
     * @param serialNumber the value for tb_withdrawals.serial_number
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public void setSerialNumber(Integer serialNumber) {
        this.serialNumber = serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdrawals.daybook_serial_number
     *
     * @return the value of tb_withdrawals.daybook_serial_number
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public Long getDaybookSerialNumber() {
        return daybookSerialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdrawals.daybook_serial_number
     *
     * @param daybookSerialNumber the value for tb_withdrawals.daybook_serial_number
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public void setDaybookSerialNumber(Long daybookSerialNumber) {
        this.daybookSerialNumber = daybookSerialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdrawals.seller_id
     *
     * @return the value of tb_withdrawals.seller_id
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public Integer getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdrawals.seller_id
     *
     * @param sellerId the value for tb_withdrawals.seller_id
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public void setSellerId(Integer sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdrawals.amount
     *
     * @return the value of tb_withdrawals.amount
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdrawals.amount
     *
     * @param amount the value for tb_withdrawals.amount
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdrawals.bank_id
     *
     * @return the value of tb_withdrawals.bank_id
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public Integer getBankId() {
        return bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdrawals.bank_id
     *
     * @param bankId the value for tb_withdrawals.bank_id
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public void setBankId(Integer bankId) {
        this.bankId = bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdrawals.bank_name
     *
     * @return the value of tb_withdrawals.bank_name
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdrawals.bank_name
     *
     * @param bankName the value for tb_withdrawals.bank_name
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdrawals.bank_province
     *
     * @return the value of tb_withdrawals.bank_province
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public String getBankProvince() {
        return bankProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdrawals.bank_province
     *
     * @param bankProvince the value for tb_withdrawals.bank_province
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public void setBankProvince(String bankProvince) {
        this.bankProvince = bankProvince == null ? null : bankProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdrawals.bank_city
     *
     * @return the value of tb_withdrawals.bank_city
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public String getBankCity() {
        return bankCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdrawals.bank_city
     *
     * @param bankCity the value for tb_withdrawals.bank_city
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public void setBankCity(String bankCity) {
        this.bankCity = bankCity == null ? null : bankCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdrawals.bank_full_name
     *
     * @return the value of tb_withdrawals.bank_full_name
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public String getBankFullName() {
        return bankFullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdrawals.bank_full_name
     *
     * @param bankFullName the value for tb_withdrawals.bank_full_name
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public void setBankFullName(String bankFullName) {
        this.bankFullName = bankFullName == null ? null : bankFullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdrawals.account_code
     *
     * @return the value of tb_withdrawals.account_code
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public String getAccountCode() {
        return accountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdrawals.account_code
     *
     * @param accountCode the value for tb_withdrawals.account_code
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public void setAccountCode(String accountCode) {
        this.accountCode = accountCode == null ? null : accountCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdrawals.name
     *
     * @return the value of tb_withdrawals.name
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdrawals.name
     *
     * @param name the value for tb_withdrawals.name
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdrawals.nickname
     *
     * @return the value of tb_withdrawals.nickname
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdrawals.nickname
     *
     * @param nickname the value for tb_withdrawals.nickname
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdrawals.apply_people
     *
     * @return the value of tb_withdrawals.apply_people
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public String getApplyPeople() {
        return applyPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdrawals.apply_people
     *
     * @param applyPeople the value for tb_withdrawals.apply_people
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public void setApplyPeople(String applyPeople) {
        this.applyPeople = applyPeople == null ? null : applyPeople.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdrawals.apply_time
     *
     * @return the value of tb_withdrawals.apply_time
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public DateTime getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdrawals.apply_time
     *
     * @param applyTime the value for tb_withdrawals.apply_time
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public void setApplyTime(DateTime applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdrawals.handle_people
     *
     * @return the value of tb_withdrawals.handle_people
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public String getHandlePeople() {
        return handlePeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdrawals.handle_people
     *
     * @param handlePeople the value for tb_withdrawals.handle_people
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public void setHandlePeople(String handlePeople) {
        this.handlePeople = handlePeople == null ? null : handlePeople.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdrawals.handle_time
     *
     * @return the value of tb_withdrawals.handle_time
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public DateTime getHandleTime() {
        return handleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdrawals.handle_time
     *
     * @param handleTime the value for tb_withdrawals.handle_time
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public void setHandleTime(DateTime handleTime) {
        this.handleTime = handleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdrawals.status
     *
     * @return the value of tb_withdrawals.status
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdrawals.status
     *
     * @param status the value for tb_withdrawals.status
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdrawals.status_before_freezing
     *
     * @return the value of tb_withdrawals.status_before_freezing
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public Byte getStatusBeforeFreezing() {
        return statusBeforeFreezing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdrawals.status_before_freezing
     *
     * @param statusBeforeFreezing the value for tb_withdrawals.status_before_freezing
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public void setStatusBeforeFreezing(Byte statusBeforeFreezing) {
        this.statusBeforeFreezing = statusBeforeFreezing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdrawals.preprocess_time
     *
     * @return the value of tb_withdrawals.preprocess_time
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public Byte getPreprocessTime() {
        return preprocessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdrawals.preprocess_time
     *
     * @param preprocessTime the value for tb_withdrawals.preprocess_time
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public void setPreprocessTime(Byte preprocessTime) {
        this.preprocessTime = preprocessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdrawals.agree_time
     *
     * @return the value of tb_withdrawals.agree_time
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public DateTime getAgreeTime() {
        return agreeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdrawals.agree_time
     *
     * @param agreeTime the value for tb_withdrawals.agree_time
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public void setAgreeTime(DateTime agreeTime) {
        this.agreeTime = agreeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdrawals.is_modify
     *
     * @return the value of tb_withdrawals.is_modify
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public Byte getIsModify() {
        return isModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdrawals.is_modify
     *
     * @param isModify the value for tb_withdrawals.is_modify
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public void setIsModify(Byte isModify) {
        this.isModify = isModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdrawals.account_type
     *
     * @return the value of tb_withdrawals.account_type
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public Byte getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdrawals.account_type
     *
     * @param accountType the value for tb_withdrawals.account_type
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public void setAccountType(Byte accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdrawals.real_poundage
     *
     * @return the value of tb_withdrawals.real_poundage
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public Integer getRealPoundage() {
        return realPoundage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdrawals.real_poundage
     *
     * @param realPoundage the value for tb_withdrawals.real_poundage
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public void setRealPoundage(Integer realPoundage) {
        this.realPoundage = realPoundage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdrawals.poundage
     *
     * @return the value of tb_withdrawals.poundage
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public Integer getPoundage() {
        return poundage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdrawals.poundage
     *
     * @param poundage the value for tb_withdrawals.poundage
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public void setPoundage(Integer poundage) {
        this.poundage = poundage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdrawals.real_amount
     *
     * @return the value of tb_withdrawals.real_amount
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public Integer getRealAmount() {
        return realAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdrawals.real_amount
     *
     * @param realAmount the value for tb_withdrawals.real_amount
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public void setRealAmount(Integer realAmount) {
        this.realAmount = realAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdrawals.task_id
     *
     * @return the value of tb_withdrawals.task_id
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdrawals.task_id
     *
     * @param taskId the value for tb_withdrawals.task_id
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdrawals.complete_time
     *
     * @return the value of tb_withdrawals.complete_time
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public DateTime getCompleteTime() {
        return completeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdrawals.complete_time
     *
     * @param completeTime the value for tb_withdrawals.complete_time
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public void setCompleteTime(DateTime completeTime) {
        this.completeTime = completeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdrawals.failure_reason
     *
     * @return the value of tb_withdrawals.failure_reason
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public String getFailureReason() {
        return failureReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdrawals.failure_reason
     *
     * @param failureReason the value for tb_withdrawals.failure_reason
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public void setFailureReason(String failureReason) {
        this.failureReason = failureReason == null ? null : failureReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdrawals.image_path
     *
     * @return the value of tb_withdrawals.image_path
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdrawals.image_path
     *
     * @param imagePath the value for tb_withdrawals.image_path
     *
     * @mbggenerated Fri Jun 12 17:00:22 CST 2015
     */
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath == null ? null : imagePath.trim();
    }
}